<?php require_once('templates/headers/opening.tpl.php'); ?>

<!-- Specific Page Data -->
<?php $title       = 'Sizing Utilities - Multipurpose Modern Minimal Responsive HTML 5 Templates'; ?>
<?php $keywords    = 'HTML5 Template, CSS3, Bootstrap theme, Technology Web Theme, Modern HTML Template, Ventech, Masonry'; ?>
<?php $description = 'Sizing Utilities for Multipurpose Modern Minimal Responsive HTML 5 Templates'; ?>
<?php $active_menu        = 'menu-features';   // To set active on the same id of primary menu ?>
<?php
// Specific Configuration for Page

?>

<!-- End of Data -->

<?php require_once('templates/headers/'.$header.'.tpl.php'); ?>


<section class="section section-header full-layout">
    <div class="height-xs-5 height-md-6" >
        <div class="parallax-bg bg-tech-key" data-parallax="-.6">
            <div class="content-title">
                <div class="container">
                    <ul class="breadcrumb">
                        <li>
                            <a href="index.php">
                                Home
                            </a>
                        </li>
                        <li>
                            <a href="features-typography.php">
                                Features
                            </a>
                        </li>
                        <li>
                            <a href="features-utilities-typography.php">
                                Comprehensive Utilities
                            </a>
                        </li>
                        <li class="active">
                            Sizing
                        </li>
                    </ul>
                    <h1 class="title-text">
                        Sizing Utilities
                    </h1>
                    <div class="subtitle-text">
                        Can be used to any element, fit perfectly for our mega menu.
                    </div>
                </div>
            </div>
        </div>
        <div class="full-size bg-pat-dark-6 op-50"> <!-- change cover with any bg class -->
        </div>        
    </div>
</section>
<!-- .section -->


<section class="main-content full-layout">
    <div class="container">
        <h2 class="section-title">
            Fixed Width / Height Responsive
        </h2>
        <div class="table-responsive">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>
                            Width / Height
                        </th>
                        <th class="text-center">
                            Extra small<br>
                            <small>
                                &lt;544px
                            </small>
                        </th>
                        <th class="text-center">
                            Small<br>
                            <small>
                                ≥544px
                            </small>
                        </th>
                        <th class="text-center">
                            Medium<br>
                            <small>
                                ≥768px
                            </small>
                        </th>
                        <th class="text-center">
                            Large<br>
                            <small>
                                ≥992px
                            </small>
                        </th>
                        <th class="text-center">
                            Extra large<br>
                            <small>
                                ≥1200px
                            </small>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th>
                            auto
                        </th>
                        <td>
                            <code>
                                width-xs-auto
                            </code>
                            /
                            <code>
                                height-xs-auto
                            </code>
                        </td>
                        <td>
                            <code>
                                width-sm-auto
                            </code>
                            /
                            <code>
                                height-sm-auto
                            </code>

                        </td>
                        <td>
                            <code>
                                width-md-auto
                            </code>
                            /
                            <code>
                                height-md-auto
                            </code>

                        </td>
                        <td>
                            <code>
                                width-lg-auto
                            </code>
                            /
                            <code>
                                height-lg-auto
                            </code>

                        </td>
                        <td>
                            <code>
                                width-xl-auto
                            </code>
                            /
                            <code>
                                height-xl-auto
                            </code>

                        </td>
                    </tr>
                    <tr>
                        <th>
                            60px
                        </th>
                        <td>
                            <code>
                                width-xs-1
                            </code>
                            /
                            <code>
                                height-xs-1
                            </code>
                        </td>
                        <td>
                            <code>
                                width-sm-1
                            </code>
                            /
                            <code>
                                height-sm-1
                            </code>

                        </td>
                        <td>
                            <code>
                                width-md-1
                            </code>
                            /
                            <code>
                                height-md-1
                            </code>

                        </td>
                        <td>
                            <code>
                                width-lg-1
                            </code>
                            /
                            <code>
                                height-lg-1
                            </code>

                        </td>
                        <td>
                            <code>
                                width-xl-1
                            </code>
                            /
                            <code>
                                height-xl-1
                            </code>

                        </td>
                    </tr>
                    <tr>
                        <th>
                            120px
                        </th>
                        <td>
                            <code>
                                width-xs-2
                            </code>
                            /
                            <code>
                                height-xs-2
                            </code>
                        </td>
                        <td>
                            <code>
                                width-sm-2
                            </code>
                            /
                            <code>
                                height-sm-2
                            </code>

                        </td>
                        <td>
                            <code>
                                width-md-2
                            </code>
                            /
                            <code>
                                height-md-2
                            </code>

                        </td>
                        <td>
                            <code>
                                width-lg-2
                            </code>
                            /
                            <code>
                                height-lg-2
                            </code>

                        </td>
                        <td>
                            <code>
                                width-xl-2
                            </code>
                            /
                            <code>
                                height-xl-2
                            </code>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            200px
                        </th>
                        <td>
                            <code>
                                width-xs-3
                            </code>
                            /
                            <code>
                                height-xs-3
                            </code>
                        </td>
                        <td>
                            <code>
                                width-sm-3
                            </code>
                            /
                            <code>
                                height-sm-3
                            </code>

                        </td>
                        <td>
                            <code>
                                width-md-3
                            </code>
                            /
                            <code>
                                height-md-3
                            </code>

                        </td>
                        <td>
                            <code>
                                width-lg-3
                            </code>
                            /
                            <code>
                                height-lg-3
                            </code>

                        </td>
                        <td>
                            <code>
                                width-xl-3
                            </code>
                            /
                            <code>
                                height-xl-3
                            </code>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            240px
                        </th>
                        <td>
                            <code>
                                width-xs-4
                            </code>
                            /
                            <code>
                                height-xs-4
                            </code>
                        </td>
                        <td>
                            <code>
                                width-sm-4
                            </code>
                            /
                            <code>
                                height-sm-4
                            </code>

                        </td>
                        <td>
                            <code>
                                width-md-4
                            </code>
                            /
                            <code>
                                height-md-4
                            </code>

                        </td>
                        <td>
                            <code>
                                width-lg-4
                            </code>
                            /
                            <code>
                                height-lg-4
                            </code>

                        </td>
                        <td>
                            <code>
                                width-xl-4
                            </code>
                            /
                            <code>
                                height-xl-4
                            </code>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            360px
                        </th>
                        <td>
                            <code>
                                width-xs-5
                            </code>
                            /
                            <code>
                                height-xs-5
                            </code>
                        </td>
                        <td>
                            <code>
                                width-sm-5
                            </code>
                            /
                            <code>
                                height-sm-5
                            </code>

                        </td>
                        <td>
                            <code>
                                width-md-5
                            </code>
                            /
                            <code>
                                height-md-5
                            </code>

                        </td>
                        <td>
                            <code>
                                width-lg-5
                            </code>
                            /
                            <code>
                                height-lg-5
                            </code>

                        </td>
                        <td>
                            <code>
                                width-xl-5
                            </code>
                            /
                            <code>
                                height-xl-5
                            </code>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            480px
                        </th>
                        <td>
                            <code>
                                width-xs-6
                            </code>
                            /
                            <code>
                                height-xs-6
                            </code>
                        </td>
                        <td>
                            <code>
                                width-sm-6
                            </code>
                            /
                            <code>
                                height-sm-6
                            </code>

                        </td>
                        <td>
                            <code>
                                width-md-6
                            </code>
                            /
                            <code>
                                height-md-6
                            </code>

                        </td>
                        <td>
                            <code>
                                width-lg-6
                            </code>
                            /
                            <code>
                                height-lg-6
                            </code>

                        </td>
                        <td>
                            <code>
                                width-xl-6
                            </code>
                            /
                            <code>
                                height-xl-6
                            </code>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            640px
                        </th>
                        <td>
                            <code>
                                width-xs-7
                            </code>
                            /
                            <code>
                                height-xs-7
                            </code>
                        </td>
                        <td>
                            <code>
                                width-sm-7
                            </code>
                            /
                            <code>
                                height-sm-7
                            </code>

                        </td>
                        <td>
                            <code>
                                width-md-7
                            </code>
                            /
                            <code>
                                height-md-7
                            </code>

                        </td>
                        <td>
                            <code>
                                width-lg-7
                            </code>
                            /
                            <code>
                                height-lg-7
                            </code>

                        </td>
                        <td>
                            <code>
                                width-xl-7
                            </code>
                            /
                            <code>
                                height-xl-7
                            </code>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            720px
                        </th>
                        <td>
                            <code>
                                width-xs-8
                            </code>
                            /
                            <code>
                                height-xs-8
                            </code>
                        </td>
                        <td>
                            <code>
                                width-sm-8
                            </code>
                            /
                            <code>
                                height-sm-8
                            </code>

                        </td>
                        <td>
                            <code>
                                width-md-8
                            </code>
                            /
                            <code>
                                height-md-8
                            </code>

                        </td>
                        <td>
                            <code>
                                width-lg-8
                            </code>
                            /
                            <code>
                                height-lg-8
                            </code>

                        </td>
                        <td>
                            <code>
                                width-xl-8
                            </code>
                            /
                            <code>
                                height-xl-8
                            </code>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            960px
                        </th>
                        <td>
                            <code>
                                width-xs-9
                            </code>
                            /
                            <code>
                                height-xs-9
                            </code>
                        </td>
                        <td>
                            <code>
                                width-sm-9
                            </code>
                            /
                            <code>
                                height-sm-9
                            </code>

                        </td>
                        <td>
                            <code>
                                width-md-9
                            </code>
                            /
                            <code>
                                height-md-9
                            </code>

                        </td>
                        <td>
                            <code>
                                width-lg-9
                            </code>
                            /
                            <code>
                                height-lg-9
                            </code>

                        </td>
                        <td>
                            <code>
                                width-xl-9
                            </code>
                            /
                            <code>
                                height-xl-9
                            </code>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            1130px
                        </th>
                        <td>
                            <code>
                                width-xs-10
                            </code>
                            /
                            <code>
                                height-xs-10
                            </code>
                        </td>
                        <td>
                            <code>
                                width-sm-10
                            </code>
                            /
                            <code>
                                height-sm-10
                            </code>

                        </td>
                        <td>
                            <code>
                                width-md-10
                            </code>
                            /
                            <code>
                                height-md-10
                            </code>

                        </td>
                        <td>
                            <code>
                                width-lg-10
                            </code>
                            /
                            <code>
                                height-lg-10
                            </code>

                        </td>
                        <td>
                            <code>
                                width-xl-10
                            </code>
                            /
                            <code>
                                height-xl-10
                            </code>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <br/>
        <div class="row">
            <div class="col-md-4">
                <h2 class="section-title">
                    Width Percentage
                </h2>
                <div class="table-responsive">
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>

                                </th>
                                <th class="text-center">
                                    CSS
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th>
                                    10%
                                </th>
                                <td>
                                    <code>
                                        width-10
                                    </code>
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    20%
                                </th>
                                <td>
                                    <code>
                                        width-20
                                    </code>
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    30%
                                </th>
                                <td>
                                    <code>
                                        width-30
                                    </code>
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    40%
                                </th>
                                <td>
                                    <code>
                                        width-40
                                    </code>
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    50%
                                </th>
                                <td>
                                    <code>
                                        width-50
                                    </code>
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    60%
                                </th>
                                <td>
                                    <code>
                                        width-60
                                    </code>
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    70%
                                </th>
                                <td>
                                    <code>
                                        width-70
                                    </code>
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    80%
                                </th>
                                <td>
                                    <code>
                                        width-80
                                    </code>
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    90%
                                </th>
                                <td>
                                    <code>
                                        width-90
                                    </code>
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    100%
                                </th>
                                <td>
                                    <code>
                                        width-100
                                    </code>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col-md-8">
                <h2 class="section-title">
                    Padding / Margin
                </h2>
                <div class="table-responsive">
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>

                                </th>
                                <th class="text-center">
                                    All
                                </th>
                                <th class="text-center">
                                    Top
                                </th>
                                <th class="text-center">
                                    Right
                                </th>
                                <th class="text-center">
                                    Bottom
                                </th>
                                <th class="text-center">
                                    Left
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th>
                                    0px
                                </th>
                                <td>
                                    <code>
                                        pd-0
                                    </code>
                                    /
                                    <code>
                                        mg-0
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdt-0
                                    </code>
                                    /
                                    <code>
                                        mgt-0
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdr-0
                                    </code>
                                    /
                                    <code>
                                        mgr-0
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdb-0
                                    </code>
                                    /
                                    <code>
                                        mgb-0
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdl-0
                                    </code>
                                    /
                                    <code>
                                        mgl-0
                                    </code>
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    5px
                                </th>
                                <td>
                                    <code>
                                        pd-5
                                    </code>
                                    /
                                    <code>
                                        mg-5
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdt-5
                                    </code>
                                    /
                                    <code>
                                        mgt-5
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdr-5
                                    </code>
                                    /
                                    <code>
                                        mgr-5
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdb-5
                                    </code>
                                    /
                                    <code>
                                        mgb-5
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdl-5
                                    </code>
                                    /
                                    <code>
                                        mgl-5
                                    </code>
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    10px
                                </th>
                                <td>
                                    <code>
                                        pd-10
                                    </code>
                                    /
                                    <code>
                                        mg-10
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdt-10
                                    </code>
                                    /
                                    <code>
                                        mgt-10
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdr-10
                                    </code>
                                    /
                                    <code>
                                        mgr-10
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdb-10
                                    </code>
                                    /
                                    <code>
                                        mgb-10
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdl-10
                                    </code>
                                    /
                                    <code>
                                        mgl-10
                                    </code>
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    15px
                                </th>
                                <td>
                                    <code>
                                        pd-15
                                    </code>
                                    /
                                    <code>
                                        mg-15
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdt-15
                                    </code>
                                    /
                                    <code>
                                        mgt-15
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdr-15
                                    </code>
                                    /
                                    <code>
                                        mgr-15
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdb-15
                                    </code>
                                    /
                                    <code>
                                        mgb-15
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdl-15
                                    </code>
                                    /
                                    <code>
                                        mgl-15
                                    </code>
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    20px
                                </th>
                                <td>
                                    <code>
                                        pd-20
                                    </code>
                                    /
                                    <code>
                                        mg-20
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdt-20
                                    </code>
                                    /
                                    <code>
                                        mgt-20
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdr-20
                                    </code>
                                    /
                                    <code>
                                        mgr-20
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdb-20
                                    </code>
                                    /
                                    <code>
                                        mgb-20
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdl-20
                                    </code>
                                    /
                                    <code>
                                        mgl-20
                                    </code>
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    25px
                                </th>
                                <td>
                                    <code>
                                        pd-25
                                    </code>
                                    /
                                    <code>
                                        mg-25
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdt-25
                                    </code>
                                    /
                                    <code>
                                        mgt-25
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdr-25
                                    </code>
                                    /
                                    <code>
                                        mgr-25
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdb-25
                                    </code>
                                    /
                                    <code>
                                        mgb-25
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdl-25
                                    </code>
                                    /
                                    <code>
                                        mgl-25
                                    </code>
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    30px
                                </th>
                                <td>
                                    <code>
                                        pd-30
                                    </code>
                                    /
                                    <code>
                                        mg-30
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdt-30
                                    </code>
                                    /
                                    <code>
                                        mgt-30
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdr-30
                                    </code>
                                    /
                                    <code>
                                        mgr-30
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdb-30
                                    </code>
                                    /
                                    <code>
                                        mgb-30
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdl-30
                                    </code>
                                    /
                                    <code>
                                        mgl-30
                                    </code>
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    35px
                                </th>
                                <td>
                                    <code>
                                        pd-35
                                    </code>
                                    /
                                    <code>
                                        mg-35
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdt-35
                                    </code>
                                    /
                                    <code>
                                        mgt-35
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdr-35
                                    </code>
                                    /
                                    <code>
                                        mgr-35
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdb-35
                                    </code>
                                    /
                                    <code>
                                        mgb-35
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdl-35
                                    </code>
                                    /
                                    <code>
                                        mgl-35
                                    </code>
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    40px
                                </th>
                                <td>
                                    <code>
                                        pd-40
                                    </code>
                                    /
                                    <code>
                                        mg-40
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdt-40
                                    </code>
                                    /
                                    <code>
                                        mgt-40
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdr-40
                                    </code>
                                    /
                                    <code>
                                        mgr-40
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdb-40
                                    </code>
                                    /
                                    <code>
                                        mgb-40
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdl-40
                                    </code>
                                    /
                                    <code>
                                        mgl-40
                                    </code>
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    45px
                                </th>
                                <td>
                                    <code>
                                        pd-45
                                    </code>
                                    /
                                    <code>
                                        mg-45
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdt-45
                                    </code>
                                    /
                                    <code>
                                        mgt-45
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdr-45
                                    </code>
                                    /
                                    <code>
                                        mgr-45
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdb-45
                                    </code>
                                    /
                                    <code>
                                        mgb-45
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdl-45
                                    </code>
                                    /
                                    <code>
                                        mgl-45
                                    </code>
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    50px
                                </th>
                                <td>
                                    <code>
                                        pd-50
                                    </code>
                                    /
                                    <code>
                                        mg-50
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdt-50
                                    </code>
                                    /
                                    <code>
                                        mgt-50
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdr-50
                                    </code>
                                    /
                                    <code>
                                        mgr-50
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdb-50
                                    </code>
                                    /
                                    <code>
                                        mgb-50
                                    </code>
                                </td>
                                <td>
                                    <code>
                                        pdl-50
                                    </code>
                                    /
                                    <code>
                                        mgl-50
                                    </code>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <br/>
        <h2 class="section-title">
            Margin Bottom Responsive
        </h2>
        <div class="table-responsive">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>
                            Margin Bottom
                        </th>
                        <th class="text-center">
                            Extra small<br>
                            <small>
                                &lt;544px
                            </small>
                        </th>
                        <th class="text-center">
                            Small<br>
                            <small>
                                ≥544px
                            </small>
                        </th>
                        <th class="text-center">
                            Medium<br>
                            <small>
                                ≥768px
                            </small>
                        </th>
                        <th class="text-center">
                            Large<br>
                            <small>
                                ≥992px
                            </small>
                        </th>
                        <th class="text-center">
                            Extra large<br>
                            <small>
                                ≥1200px
                            </small>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th>
                            0
                        </th>
                        <td>
                            <code>
                                mgb-xs-0
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-sm-0
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-md-0
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-lg-0
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-xl-0
                            </code>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            5px
                        </th>
                        <td>
                            <code>
                                mgb-xs-5
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-sm-5
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-md-5
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-lg-5
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-xl-5
                            </code>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            10px
                        </th>
                        <td>
                            <code>
                                mgb-xs-10
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-sm-10
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-md-10
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-lg-10
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-xl-10
                            </code>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            15px
                        </th>
                        <td>
                            <code>
                                mgb-xs-15
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-sm-15
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-md-15
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-lg-15
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-xl-15
                            </code>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            20px
                        </th>
                        <td>
                            <code>
                                mgb-xs-20
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-sm-20
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-md-20
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-lg-20
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-xl-20
                            </code>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            25px
                        </th>
                        <td>
                            <code>
                                mgb-xs-25
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-sm-25
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-md-25
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-lg-25
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-xl-25
                            </code>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            30px
                        </th>
                        <td>
                            <code>
                                mgb-xs-30
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-sm-30
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-md-30
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-lg-30
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-xl-30
                            </code>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            35px
                        </th>
                        <td>
                            <code>
                                mgb-xs-35
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-sm-35
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-md-35
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-lg-35
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-xl-35
                            </code>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            40px
                        </th>
                        <td>
                            <code>
                                mgb-xs-40
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-sm-40
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-md-40
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-lg-40
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-xl-40
                            </code>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            45px
                        </th>
                        <td>
                            <code>
                                mgb-xs-45
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-sm-45
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-md-45
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-lg-45
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-xl-45
                            </code>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            50px
                        </th>
                        <td>
                            <code>
                                mgb-xs-50
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-sm-50
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-md-50
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-lg-50
                            </code>
                        </td>
                        <td>
                            <code>
                                mgb-xl-50
                            </code>
                        </td>
                    </tr>


                </tbody>
            </table>
        </div>

    </div>
    <!-- container -->
</section>
<!-- .main-content -->

<?php require_once('templates/footers/'.$footer.'.tpl.php'); ?>

<!-- Specific Page Scripts Put Here -->


<!-- Specific Page Scripts END -->

<?php require_once('templates/footers/closing.tpl.php'); ?>